"""Admin support boundary (ADM-01 and related); contracts + orchestration slice."""

from app.admin_support.adm01_endpoint import (
    Adm01EndpointResponse,
    Adm01InboundRequest,
    Adm01OutboundSummary,
    execute_adm01_endpoint,
)
from app.admin_support.adm02_endpoint import (
    Adm02DiagnosticsHandlerLike,
    Adm02EndpointResponse,
    Adm02InboundRequest,
    Adm02OutboundSummary,
    execute_adm02_endpoint,
)
from app.admin_support.adm01_lookup import Adm01LookupHandler
from app.admin_support.adm01_postgres_issuance_read_adapter import Adm01PostgresIssuanceReadAdapter
from app.admin_support.adm02_fact_of_access_audit_adapter import (
    Adm02FactOfAccessPersistenceAuditAdapter,
)
from app.admin_support.adm02_billing_facts_ledger_adapter import (
    Adm02BillingFactsLedgerReadAdapter,
)
from app.admin_support.adm02_quarantine_mismatch_adapter import Adm02QuarantineMismatchReadAdapter
from app.admin_support.adm02_reconciliation_runs_adapter import Adm02ReconciliationRunsReadAdapter
from app.admin_support.adm02_diagnostics import ADM02_CAPABILITY_CLASS, Adm02DiagnosticsHandler
from app.admin_support.adm02_wiring import build_adm02_internal_diagnostics_http_app
from app.admin_support.authorization import AllowlistAdm01Authorization, AllowlistAdm02Authorization
from app.admin_support.contracts import (
    AdminActorRef,
    AdminPolicyFlag,
    AdminTargetLookup,
    Adm01AuthorizationPort,
    Adm01EntitlementReadPort,
    Adm01IdentityResolvePort,
    Adm01IssuanceReadPort,
    Adm01LookupInput,
    Adm01LookupOutcome,
    Adm01LookupResult,
    Adm01LookupSummary,
    Adm01PolicyReadPort,
    Adm01RedactionPort,
    Adm01SubscriptionReadPort,
    Adm01SubscriptionStatusSummary,
    Adm02AuthorizationPort,
    Adm02BillingFactsCategory,
    Adm02BillingFactsDiagnostics,
    Adm02BillingFactsReadPort,
    Adm02DiagnosticsInput,
    Adm02DiagnosticsOutcome,
    Adm02DiagnosticsResult,
    Adm02DiagnosticsSummary,
    Adm02FactOfAccessAuditPort,
    Adm02FactOfAccessAuditRecord,
    Adm02FactOfAccessDisclosureCategory,
    Adm02QuarantineDiagnostics,
    Adm02QuarantineMarker,
    Adm02QuarantineReadPort,
    Adm02QuarantineReasonCode,
    Adm02ReconciliationDiagnostics,
    Adm02ReconciliationReadPort,
    Adm02ReconciliationRunMarker,
    Adm02RedactionPort,
    EntitlementSummary,
    EntitlementSummaryCategory,
    InternalUserTarget,
    InternalAdminPrincipalExtractionInput,
    InternalAdminPrincipalExtractionOutcome,
    InternalAdminPrincipalExtractionResult,
    InternalAdminPrincipalExtractor,
    IssuanceOperationalState,
    IssuanceOperationalSummary,
    RedactionMarker,
    TelegramUserTarget,
)

__all__ = [
    "ADM02_CAPABILITY_CLASS",
    "Adm01EndpointResponse",
    "Adm01InboundRequest",
    "Adm01OutboundSummary",
    "Adm02DiagnosticsHandlerLike",
    "Adm02EndpointResponse",
    "Adm02InboundRequest",
    "Adm02OutboundSummary",
    "AllowlistAdm01Authorization",
    "AllowlistAdm02Authorization",
    "AdminActorRef",
    "AdminPolicyFlag",
    "AdminTargetLookup",
    "InternalAdminPrincipalExtractionInput",
    "InternalAdminPrincipalExtractionOutcome",
    "InternalAdminPrincipalExtractionResult",
    "InternalAdminPrincipalExtractor",
    "Adm01AuthorizationPort",
    "Adm01EntitlementReadPort",
    "Adm01IdentityResolvePort",
    "Adm01IssuanceReadPort",
    "Adm01LookupHandler",
    "Adm01PostgresIssuanceReadAdapter",
    "Adm02AuthorizationPort",
    "Adm02BillingFactsCategory",
    "Adm02BillingFactsDiagnostics",
    "Adm02BillingFactsReadPort",
    "Adm02BillingFactsLedgerReadAdapter",
    "Adm02QuarantineMismatchReadAdapter",
    "Adm02ReconciliationRunsReadAdapter",
    "Adm02DiagnosticsHandler",
    "Adm02FactOfAccessPersistenceAuditAdapter",
    "Adm02DiagnosticsInput",
    "build_adm02_internal_diagnostics_http_app",
    "Adm02DiagnosticsOutcome",
    "Adm02DiagnosticsResult",
    "Adm02DiagnosticsSummary",
    "Adm02FactOfAccessAuditPort",
    "Adm02FactOfAccessAuditRecord",
    "Adm02FactOfAccessDisclosureCategory",
    "Adm02QuarantineDiagnostics",
    "Adm02QuarantineMarker",
    "Adm02QuarantineReadPort",
    "Adm02QuarantineReasonCode",
    "Adm02ReconciliationDiagnostics",
    "Adm02ReconciliationReadPort",
    "Adm02ReconciliationRunMarker",
    "Adm02RedactionPort",
    "Adm01LookupInput",
    "Adm01LookupOutcome",
    "Adm01LookupResult",
    "Adm01LookupSummary",
    "Adm01PolicyReadPort",
    "Adm01RedactionPort",
    "Adm01SubscriptionReadPort",
    "Adm01SubscriptionStatusSummary",
    "EntitlementSummary",
    "EntitlementSummaryCategory",
    "InternalUserTarget",
    "IssuanceOperationalState",
    "IssuanceOperationalSummary",
    "RedactionMarker",
    "TelegramUserTarget",
    "execute_adm01_endpoint",
    "execute_adm02_endpoint",
]
